name: flutter_data_json_api_adapter
description: JSON:API adapter for Flutter Data
version: 0.1.7
homepage: https://github.com/flutterdata/flutter_data_json_api_adapter

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter_data: ^0.5.14
  json_api: ^4.3.0

# dependency_overrides:
#   flutter_data:
#     path: ../flutter_data
dev_dependencies:
  build_runner: ^1.7.4
  build_test: ^0.10.11
  freezed: ^0.12.1
  freezed_annotation: ^0.12.0
  hive: ^1.4.1+1
  json_annotation: ^3.0.1
  json_serializable: ^3.2.5
  matcher: ^0.12.6
  mockito: ^4.1.1
  pedantic: ^1.8.0+1
  riverpod: ">=0.11.0 <1.0.0"
  source_gen_test: ^0.1.0
  test: ^1.9.4
