name: flutter_data_json_api_adapter
description: JSON:API adapter for Flutter Data
version: 0.4.0
homepage: https://github.com/flutterdata/flutter_data_json_api_adapter

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  collection: ^1.15.0
  flutter_data: ^1.0.0
  json_api: ^5.0.4

dev_dependencies:
  build_runner: ^2.0.4
  build_test: ^2.1.0
  freezed: ^0.14.2
  freezed_annotation: ^0.14.2
  hive: ^2.0.4
  http: ^0.13.3
  json_annotation: ">=4.3.0 <4.4.0"
  json_serializable: ^6.0.1
  mockito: ^5.0.10
  recase: ^4.0.0
  riverpod: ^1.0.0
  test: ^1.17.8
