name: flutter_data_json_api_adapter
description: JSON:API adapter for Flutter Data
version: 0.9.0
homepage: https://github.com/flutterdata/flutter_data_json_api_adapter

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  collection: ^1.15.0
  flutter_data: ^1.6.0
  json_api: ^7.0.0

# dependency_overrides:
#   flutter_data:
#     path: ../flutter_data

dev_dependencies:
  build_runner: ^2.0.4
  build_test: ^2.1.0
  freezed: ^2.4.7
  freezed_annotation: ^2.4.1
  hive: ^2.0.4
  http: ^1.2.0
  json_annotation: ^4.7.0
  json_serializable: ^6.1.4
  lints: ^3.0.0
  mockito: ^5.0.10
  riverpod: ^2.5.1
  test: ^1.17.8
